{% set name = "flake8-simplify" %}
{% set version = "0.31.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3830f39afed7dc76d6a6f4db006f5a460e1cb8ebe82e08c1d99c5f4e24fab26d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - flake8 >=3.7

test:
  requires:
    - python {{ python_min }}
  commands:
    - flake8 --version | grep flake8_simplify

about:
  home: https://github.com/MartinThoma/flake8-simplify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A flake8 plugin that helps you simplify your code.
  dev_url: https://github.com/MartinThoma/flake8-simplify

extra:
  recipe-maintainers:
    - dopplershift
