{% set name = "flake8-simplify" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: c95ff1dcc1de5949af47e0087cbf1164445881131b15bcd7a71252670f492f4d

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - flake8 >=3.7
    - astor >=0.1

test:
  requires:
    - python {{ python_min }}
  commands:
    - flake8 --version | grep flake8_simplify

about:
  home: https://github.com/MartinThoma/flake8-simplify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A flake8 plugin that helps you simplify your code.
  dev_url: https://github.com/MartinThoma/flake8-simplify

extra:
  recipe-maintainers:
    - dopplershift
